name: bitbox_flutter
description: Flutter bindings for BitBox02 hardware wallet using Rust
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0
  ffi: ^2.1.0

  flutter_rust_bridge: 2.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  ffigen: ^11.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.bitbox.bitbox_flutter
        pluginClass: BitboxFlutterPlugin

